### ISSUE TITLE
Generating plots using blobtools view

### ISSUE THREAD

**Issue by NPPO-NL** [blobtoolkit/blobtoolkit#176]
Goodday,

I have encountered 2 issues I am hoping to get assistance with.

First, I have encountered an issue with the generation of plots.
![image](https://github.com/blobtoolkit/blobtoolkit/assets/58730987/4852fb97-8195-49be-80da-fc9cb7246ddb)

When generating plots, they are not moved to the directory specified behind the --out flag, getting stuck on the "waiting for file" section. I have also tried to generate plots without the --out flag, but the plots never appeared in the working directory. The plots do appear in firefox's default downloads directory.  I have made sure the --out location is writeable. I feel like I am missing something?

My second question relates to blob plots. These export in a square view by default, is it possible to export these over command line with circles instead?

Kind regards,
Lucas

**Comment by rjchallis** [comment]
Which version of blob tools are you using? This looks like it could be an older issue that should be fixed in the latest version.

The plots default to the square binned view if the assembly has > 2000 contains. to show the circle view instead, you can pass `--params plotShape=circle` to the blob tools view command.

If you continue to have issues, I'm working to replace the browser-based plotting with a command-line only version based on some code I've written over at https://github.com/blobtoolkit/blobtk/tree/develop (scroll down to see the `blobtk plot` options), this should be working for all the basic plots if you want to give it a go.

**Comment by NPPO-NL** [comment]
I am using blobtools 4.1.5 and, even after updating the packages in the conda environment, I am still receiving this issue. 

I moved on to blobtk and so far it is working great. Thanks for pointing this out.
